Done Profile Page
kenneth0810/CMPE133-TaskMate pull request #15
Opened 2024-11-19 21:22 UTC by AlexNguyenSJSU

3 Features of this Profile Page Completed:
1. Add Bio
2. Reset password
3. Delete Account

1 more feature I could work on is Upload the User's Image into their Account

2024-11-27 19:41 UTC, kenneth0810 commented on app/__init__.py
> +    SECRET_KEY = 'TaskMate',
For this line, we should leave it as is with os.getenv() because the secret key should be not be uploaded on Github. For this to work, you just need to create a file called .env and put it in the root directory of the project. Inside the .env file, just paste: `SECRET_KEY=key`

Replace "key" with a randomly generated secret key from running this script:

```
import secrets

secret_key = secrets.token_hex(24)

# Print the secret key
print(secret_key)
```

2024-11-27 19:44 UTC, kenneth0810 requested changes, later dismissed
Looks good! Just need to configure your environment variable in a .env file :)

2024-12-03 21:17 UTC, AlexNguyenSJSU commented on app/__init__.py
> +    SECRET_KEY = 'TaskMate',
Thanks, I understand it now! Fixed that

2024-12-06 11:06 UTC, EricksonNg approved these changes
Thank you

2024-12-06 11:12 UTC, merged